/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LaRevelaToken } from "./LaRevelaToken";
export * as factories from "./factories";
export { LaRevelaToken__factory } from "./factories/LaRevelaToken__factory";
